# Generated by Django 3.0.10 on 2020-10-03 21:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('starts', models.DateField(default=datetime.datetime.now)),
                ('finished', models.DateField(blank=True, null=True)),
                ('max_atendees_count', models.IntegerField()),
                ('price', models.FloatField(default=10.0)),
                ('remote', models.BooleanField()),
                ('test', models.DateTimeField(auto_now_add=True)),
                ('technology_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Technology')),
            ],
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('max_atendees_count__gte', 5), ('max_atendees_count__lte', 10)), name='max_atendees_count_between_5_and_10'),
        ),
    ]
